// =======================================================================================================================================================================================
																// By Maxou - www.sfpteam.fr - INTERDICTION DE RECOPIER !! //
																  // Poursuite pénal possible ! Voir amar.arma3.fr //
// =======================================================================================================================================================================================

/*
	La classe
	Le prix
	Son nom
*/


//Habits rebelles

compil_habits_civil =
[
	["U_O_Wetsuit", 200, getText (configFile >> "cfgWeapons" >> "U_O_Wetsuit" >> "displayName")],
	["U_BG_Guerrilla_6_1", 200, getText (configFile >> "cfgWeapons" >> "U_BG_Guerrilla_6_1" >> "displayName")],
	["U_B_CombatUniform_mcam_tshirt", 200, getText (configFile >> "cfgWeapons" >> "U_B_CombatUniform_mcam_tshirt" >> "displayName")],
	["U_I_G_resistanceLeader_F", 200, getText (configFile >> "cfgWeapons" >> "U_I_G_resistanceLeader_F" >> "displayName")],
	["U_I_CombatUniform_shortsleeve", 200, getText (configFile >> "cfgWeapons" >> "U_I_CombatUniform_shortsleeve" >> "displayName")],
	["U_I_OfficerUniform", 200, getText (configFile >> "cfgWeapons" >> "U_I_OfficerUniform" >> "displayName")],
	["U_O_OfficerUniform_ocamo", 200, getText (configFile >> "cfgWeapons" >> "U_O_OfficerUniform_ocamo" >> "displayName")],
	["U_B_survival_uniform", 200, getText (configFile >> "cfgWeapons" >> "U_B_survival_uniform" >> "displayName")],
	["U_B_CTRG_2", 200, getText (configFile >> "cfgWeapons" >> "U_B_CTRG_2" >> "displayName")],
	["U_BG_leader", 200, getText (configFile >> "cfgWeapons" >> "U_BG_leader" >> "displayName")],
	["U_BG_Guerilla1_1", 200, getText (configFile >> "cfgWeapons" >> "U_BG_Guerilla1_1" >> "displayName")],
	["U_I_G_Story_Protagonist_F", 200, getText (configFile >> "cfgWeapons" >> "U_I_G_Story_Protagonist_F" >> "displayName")],
	["TRYK_U_B_PCUHsW", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_B_PCUHsW" >> "displayName")],
	["TRYK_U_B_PCUHsW2", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_B_PCUHsW2" >> "displayName")],
	["TRYK_U_B_PCUHsW4", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_B_PCUHsW4" >> "displayName")],
	["TRYK_U_B_PCUHsW5", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_B_PCUHsW5" >> "displayName")],
	["TRYK_U_B_PCUHsW6", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_B_PCUHsW6" >> "displayName")],
	["TRYK_C_AOR2_T", 200, getText (configFile >> "cfgWeapons" >> "TRYK_C_AOR2_T" >> "displayName")],
	["TRYK_DMARPAT_T", 200, getText (configFile >> "cfgWeapons" >> "TRYK_DMARPAT_T" >> "displayName")],
	["TRYK_U_B_PCUHsW3nh", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_B_PCUHsW3nh" >> "displayName")],
	["TRYK_U_B_PCUHsW3", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_B_PCUHsW3" >> "displayName")],
	["TRYK_U_B_BLOD_T", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_B_BLOD_T" >> "displayName")],
	["TRYK_U_B_C01_Tsirt", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_B_C01_Tsirt" >> "displayName")],
	["TRYK_U_B_OD_OD_R_CombatUniform", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_B_OD_OD_R_CombatUniform" >> "displayName")],
	["TRYK_U_Bts_PCUs", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_Bts_PCUs" >> "displayName")],
	["TRYK_U_Bts_PCUGs", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_Bts_PCUGs" >> "displayName")],
	["TRYK_U_B_PCUHs", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_B_PCUHs" >> "displayName")],
	["TRYK_U_B_PCUGHs", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_B_PCUGHs" >> "displayName")],
	["TRYK_U_B_Sage_T", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_B_Sage_T" >> "displayName")],
	["TRYK_U_pad_hood_BKT2", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_pad_hood_BKT2" >> "displayName")],
	["TRYK_U_nohoodPcu_gry", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_nohoodPcu_gry" >> "displayName")],
	["TRYK_hoodie_FR", 200, getText (configFile >> "cfgWeapons" >> "TRYK_hoodie_FR" >> "displayName")],
	["TRYK_hoodie_Wood", 200, getText (configFile >> "cfgWeapons" >> "TRYK_hoodie_Wood" >> "displayName")],
	["TRYK_U_hood_mc", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_hood_mc" >> "displayName")],
	["TRYK_U_hood_nc", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_hood_nc" >> "displayName")],
	["TRYK_T_CSAT_PAD", 200, getText (configFile >> "cfgWeapons" >> "TRYK_T_CSAT_PAD" >> "displayName")],
	["TRYK_T_T2_PAD", 200, getText (configFile >> "cfgWeapons" >> "TRYK_T_T2_PAD" >> "displayName")],
	["TRYK_U_denim_hood_3c", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_denim_hood_3c" >> "displayName")],
	["TRYK_U_taki_BLK", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_taki_BLK" >> "displayName")],
	["TRYK_U_taki_COY", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_taki_COY" >> "displayName")],
	["TRYK_U_taki_wh", 200, getText (configFile >> "cfgWeapons" >> "TRYK_U_taki_wh" >> "displayName")],
	["TRYK_hoodie_3c", 200, getText (configFile >> "cfgWeapons" >> "TRYK_hoodie_3c" >> "displayName")],
	["TRYK_T_camo_Desert_marpat", 200, getText (configFile >> "cfgWeapons" >> "TRYK_T_camo_Desert_marpat" >> "displayName")],
	["TRYK_T_camo_Wood", 200, getText (configFile >> "cfgWeapons" >> "TRYK_T_camo_Wood" >> "displayName")],
	["TRYK_ZARATAKI", 200, getText (configFile >> "cfgWeapons" >> "TRYK_ZARATAKI" >> "displayName")],
	["TRYK_ZARATAKI2", 200, getText (configFile >> "cfgWeapons" >> "TRYK_ZARATAKI2" >> "displayName")],
	["TRYK_ZARATAKI3", 200, getText (configFile >> "cfgWeapons" >> "TRYK_ZARATAKI3" >> "displayName")],
	["U_I_C_Soldier_Para_3_F", 200, format ["(DLC) %1", getText (configFile >> "cfgWeapons" >> "U_I_C_Soldier_Para_3_F" >> "displayName")]],
	["U_I_C_Soldier_Para_4_F", 200, format ["(DLC) %1", getText (configFile >> "cfgWeapons" >> "U_I_C_Soldier_Para_4_F" >> "displayName")]],
	["U_I_C_Soldier_Para_5_F", 200, format ["(DLC) %1", getText (configFile >> "cfgWeapons" >> "U_I_C_Soldier_Para_5_F" >> "displayName")]],
	["U_I_C_Soldier_Para_1_F", 200, format ["(DLC) %1", getText (configFile >> "cfgWeapons" >> "U_I_C_Soldier_Para_1_F" >> "displayName")]],
	["U_I_C_Soldier_Para_2_F", 200, format ["(DLC) %1", getText (configFile >> "cfgWeapons" >> "U_I_C_Soldier_Para_2_F" >> "displayName")]]
];


compil_lunette_civil =
[
	["T_HoodOD", 20, getText (configFile >> "CfgGlasses" >> "T_HoodOD" >> "displayName")],
	["T_HoodTanBlk", 20, getText (configFile >> "CfgGlasses" >> "T_HoodTanBlk" >> "displayName")],
	["T_HoodACU", 20, getText (configFile >> "CfgGlasses" >> "T_HoodACU" >> "displayName")],
	["T_HoodBlk", 20, getText (configFile >> "CfgGlasses" >> "T_HoodBlk" >> "displayName")],
	["T_HoodMD", 20, getText (configFile >> "CfgGlasses" >> "T_HoodMD" >> "displayName")],
	["T_HoodMW", 20, getText (configFile >> "CfgGlasses" >> "T_HoodMW" >> "displayName")],
	["T_HoodTan", 20, getText (configFile >> "CfgGlasses" >> "T_HoodTan" >> "displayName")],
	["T_HoodBDU", 20, getText (configFile >> "CfgGlasses" >> "T_HoodBDU" >> "displayName")],
	["T_HoodTanOG", 20, getText (configFile >> "CfgGlasses" >> "T_HoodTanOG" >> "displayName")],
	["T_HoodTanCLR", 20, getText (configFile >> "CfgGlasses" >> "T_HoodTanCLR" >> "displayName")],
	["T_HoodODCLR", 20, getText (configFile >> "CfgGlasses" >> "T_HoodODCLR" >> "displayName")],
	["T_HoodODBLK", 20, getText (configFile >> "CfgGlasses" >> "T_HoodODBLK" >> "displayName")],
	["T_HoodODO", 20, getText (configFile >> "CfgGlasses" >> "T_HoodODO" >> "displayName")],
	["T_HoodACUO", 20, getText (configFile >> "CfgGlasses" >> "T_HoodACUO" >> "displayName")],
	["T_HoodACUBLK", 20, getText (configFile >> "CfgGlasses" >> "T_HoodACUBLK" >> "displayName")],
	["T_HoodACUCLR", 20, getText (configFile >> "CfgGlasses" >> "T_HoodACUCLR" >> "displayName")],
	["T_HoodBDUCLR", 20, getText (configFile >> "CfgGlasses" >> "T_HoodBDUCLR" >> "displayName")],
	["T_HoodBDUBLK", 20, getText (configFile >> "CfgGlasses" >> "T_HoodBDUBLK" >> "displayName")],
	["T_HoodBDUO", 20, getText (configFile >> "CfgGlasses" >> "T_HoodBDUO" >> "displayName")],
	["T_HoodBlkBLK", 20, getText (configFile >> "CfgGlasses" >> "T_HoodBlkBLK" >> "displayName")],
	["T_HoodBlkCLR", 20, getText (configFile >> "CfgGlasses" >> "T_HoodBlkCLR" >> "displayName")],
	["T_HoodBlkO", 20, getText (configFile >> "CfgGlasses" >> "T_HoodBlkO" >> "displayName")],
	["T_HoodMDBLK", 20, getText (configFile >> "CfgGlasses" >> "T_HoodMDBLK" >> "displayName")],
	["T_HoodMDCLR", 20, getText (configFile >> "CfgGlasses" >> "T_HoodMDCLR" >> "displayName")],
	["T_HoodMDO", 20, getText (configFile >> "CfgGlasses" >> "T_HoodMDO" >> "displayName")],
	["T_HoodMWO", 20, getText (configFile >> "CfgGlasses" >> "T_HoodMWO" >> "displayName")],
	["T_HoodMWCLR", 20, getText (configFile >> "CfgGlasses" >> "T_HoodMWCLR" >> "displayName")],
	["T_HoodMWBLK", 20, getText (configFile >> "CfgGlasses" >> "T_HoodMWBLK" >> "displayName")],
	["Shemagh_Face", 20, getText (configFile >> "CfgGlasses" >> "Shemagh_Face" >> "displayName")],
	["Shemagh_FaceTan", 20, getText (configFile >> "CfgGlasses" >> "Shemagh_FaceTan" >> "displayName")],
	["Shemagh_FaceRed", 20, getText (configFile >> "CfgGlasses" >> "Shemagh_FaceRed" >> "displayName")],
	["Shemagh_FaceGry", 20, getText (configFile >> "CfgGlasses" >> "Shemagh_FaceGry" >> "displayName")],
	["Shemagh_FaceOD", 20, getText (configFile >> "CfgGlasses" >> "Shemagh_FaceOD" >> "displayName")],
	["SAS_shemagh_Tan", 20, getText (configFile >> "CfgGlasses" >> "SAS_shemagh_Tan" >> "displayName")],
	["SAS_shemagh_OD", 20, getText (configFile >> "CfgGlasses" >> "SAS_shemagh_OD" >> "displayName")],
	["SAS_shemagh_White", 20, getText (configFile >> "CfgGlasses" >> "SAS_shemagh_White" >> "displayName")],
	["PU_shemagh_White", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_White" >> "displayName")],
	["PU_shemagh_OD", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_OD" >> "displayName")],
	["PU_shemagh_Tan", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_Tan" >> "displayName")],
	["PU_shemagh_GryCLR", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_GryCLR" >> "displayName")],
	["PU_shemagh_GryBLK", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_GryBLK" >> "displayName")],
	["PU_shemagh_GryO", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_GryO" >> "displayName")],
	["PU_shemagh_ODO", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_ODO" >> "displayName")],
	["PU_shemagh_ODCLR", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_ODCLR" >> "displayName")],
	["PU_shemagh_ODBLK", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_ODBLK" >> "displayName")],
	["PU_shemagh_TanBLK", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_TanBLK" >> "displayName")],
	["PU_shemagh_TanCLR", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_TanCLR" >> "displayName")],
	["PU_shemagh_TanO", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_TanO" >> "displayName")],
	["PU_shemagh_WhiteO", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_WhiteO" >> "displayName")],
	["PU_shemagh_WhiteBLK", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_WhiteBLK" >> "displayName")],
	["PU_shemagh_WhiteCLR", 20, getText (configFile >> "CfgGlasses" >> "PU_shemagh_WhiteCLR" >> "displayName")],
	["Balaclava_Black", 20, getText (configFile >> "CfgGlasses" >> "Balaclava_Black" >> "displayName")],
	["Balaclava_GRY", 20, getText (configFile >> "CfgGlasses" >> "Balaclava_GRY" >> "displayName")],
	["Balaclava_OD", 20, getText (configFile >> "CfgGlasses" >> "Balaclava_OD" >> "displayName")],
	["G_Lady_Blue", 20, getText (configFile >> "CfgGlasses" >> "G_Lady_Blue" >> "displayName")],
	["G_Lady_Red", 20, getText (configFile >> "CfgGlasses" >> "G_Lady_Red" >> "displayName")],
	["G_Lady_Dark", 20, getText (configFile >> "CfgGlasses" >> "G_Lady_Dark" >> "displayName")],
	["G_Lady_Mirror", 20, getText (configFile >> "CfgGlasses" >> "G_Lady_Mirror" >> "displayName")],
	["G_aviator", 20, getText (configFile >> "CfgGlasses" >> "G_aviator" >> "displayName")],
	["G_Tactical_Black", 20, getText (configFile >> "CfgGlasses" >> "G_Tactical_Black" >> "displayName")],
	["G_Sport_Red", 20, getText (configFile >> "CfgGlasses" >> "G_Sport_Red" >> "displayName")],
	["G_Sport_Checkered", 20, getText (configFile >> "CfgGlasses" >> "G_Sport_Checkered" >> "displayName")],
	["G_Sport_Greenblack", 20, getText (configFile >> "CfgGlasses" >> "G_Sport_Greenblack" >> "displayName")],
	["G_Sport_Blackyellow", 20, getText (configFile >> "CfgGlasses" >> "G_Sport_Blackyellow" >> "displayName")],
	["G_Sport_BlackWhite", 20, getText (configFile >> "CfgGlasses" >> "G_Sport_BlackWhite" >> "displayName")],
	["G_Squares_Tinted", 20, getText (configFile >> "CfgGlasses" >> "G_Squares_Tinted" >> "displayName")],
	["G_Squares", 20, getText (configFile >> "CfgGlasses" >> "G_Squares" >> "displayName")],
	["G_Shades_Red", 20, getText (configFile >> "CfgGlasses" >> "G_Shades_Red" >> "displayName")],
	["G_Shades_Green", 20, getText (configFile >> "CfgGlasses" >> "G_Shades_Green" >> "displayName")],
	["G_Shades_Black", 20, getText (configFile >> "CfgGlasses" >> "G_Shades_Black" >> "displayName")],
	["G_Lowprofile", 20, getText (configFile >> "CfgGlasses" >> "G_Lowprofile" >> "displayName")],
	["G_Combat", 20, getText (configFile >> "CfgGlasses" >> "G_Combat" >> "displayName")],
	["G_Spectacles_Tinted", 20, getText (configFile >> "CfgGlasses" >> "G_Spectacles_Tinted" >> "displayName")],
	["G_Spectacles", 20, getText (configFile >> "CfgGlasses" >> "G_Spectacles" >> "displayName")],
	["G_Tactical_Clear", 20, getText (configFile >> "CfgGlasses" >> "G_Tactical_Clear" >> "displayName")],
	["G_Sport_Blackred", 20, getText (configFile >> "CfgGlasses" >> "G_Sport_Blackred" >> "displayName")],
	["G_Shades_Blue", 20, getText (configFile >> "CfgGlasses" >> "G_Shades_Blue" >> "displayName")],
	["G_Shades_Black", 20, getText (configFile >> "CfgGlasses" >> "G_Shades_Black" >> "displayName")]
];

compil_headgear_civil =
[
	["TRYK_H_Bandana_H", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_Bandana_H" >> "displayName")],
	["TRYK_H_Booniehat_3CD", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_Booniehat_3CD" >> "displayName")],
	["TRYK_H_Booniehat_AOR1", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_Booniehat_AOR1" >> "displayName")],
	["TRYK_H_Booniehat_AOR2", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_Booniehat_AOR2" >> "displayName")],
	["TRYK_H_Booniehat_CC", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_Booniehat_CC" >> "displayName")],
	["TRYK_H_Booniehat_MARPAT_Desert", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_Booniehat_MARPAT_Desert" >> "displayName")],
	["TRYK_H_Booniehat_MARPAT_WOOD", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_Booniehat_MARPAT_WOOD" >> "displayName")],
	["TRYK_H_Booniehat_JSDF", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_Booniehat_JSDF" >> "displayName")],
	["TRYK_H_Booniehat_WOOD", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_Booniehat_WOOD" >> "displayName")],
	["TRYK_H_pakol2", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_pakol2" >> "displayName")],
	["TRYK_H_pakol", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_pakol" >> "displayName")],
	["TRYK_H_headsetcap_Glasses", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_headsetcap_Glasses" >> "displayName")],
	["TRYK_H_headsetcap_blk_Glasses", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_headsetcap_blk_Glasses" >> "displayName")],
	["TRYK_H_headsetcap_od_Glasses", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_headsetcap_od_Glasses" >> "displayName")],
	["TRYK_R_CAP_BLK", 80, getText (configFile >> "cfgWeapons" >> "TRYK_R_CAP_BLK" >> "displayName")],
	["TRYK_R_CAP_TAN", 80, getText (configFile >> "cfgWeapons" >> "TRYK_R_CAP_TAN" >> "displayName")],
	["TRYK_R_CAP_OD_US", 80, getText (configFile >> "cfgWeapons" >> "TRYK_R_CAP_OD_US" >> "displayName")],
	["TRYK_r_cap_blk_Glasses", 80, getText (configFile >> "cfgWeapons" >> "TRYK_r_cap_blk_Glasses" >> "displayName")],
	["TRYK_r_cap_od_Glasses", 80, getText (configFile >> "cfgWeapons" >> "TRYK_r_cap_od_Glasses" >> "displayName")],
	["TRYK_r_cap_tan_Glasses", 80, getText (configFile >> "cfgWeapons" >> "TRYK_r_cap_tan_Glasses" >> "displayName")],
	["TRYK_H_woolhat", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_woolhat" >> "displayName")],
	["TRYK_H_woolhat_br", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_woolhat_br" >> "displayName")],
	["TRYK_H_woolhat_cu", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_woolhat_cu" >> "displayName")],
	["TRYK_H_woolhat_tan", 80, getText (configFile >> "cfgWeapons" >> "TRYK_H_woolhat_tan" >> "displayName")],
	["H_Watchcap_blk", 80, getText (configFile >> "cfgWeapons" >> "H_Watchcap_blk" >> "displayName")],
	["H_Watchcap_khk", 80, getText (configFile >> "cfgWeapons" >> "H_Watchcap_khk" >> "displayName")],
	["H_Beret_Colonel", 80, getText (configFile >> "cfgWeapons" >> "H_Beret_Colonel" >> "displayName")],
	["H_Beret_blk", 80, getText (configFile >> "cfgWeapons" >> "H_Beret_blk" >> "displayName")],
	["H_HelmetIA", 80, getText (configFile >> "cfgWeapons" >> "H_HelmetIA" >> "displayName")],
	["H_HelmetB_light", 80, getText (configFile >> "cfgWeapons" >> "H_HelmetB_light" >> "displayName")],
	["H_HelmetB_light_desert", 80, getText (configFile >> "cfgWeapons" >> "H_HelmetB_light_desert" >> "displayName")],
	["H_HelmetB_light_grass", 80, getText (configFile >> "cfgWeapons" >> "H_HelmetB_light_grass" >> "displayName")],
	["H_HelmetB_light_black", 80, getText (configFile >> "cfgWeapons" >> "H_HelmetB_light_black" >> "displayName")],
	["H_HelmetB_light_snakeskin", 80, getText (configFile >> "cfgWeapons" >> "H_HelmetB_light_snakeskin" >> "displayName")],
	["H_HelmetB_light_sand", 80, getText (configFile >> "cfgWeapons" >> "H_HelmetB_light_sand" >> "displayName")],
	["H_Cap_tan_specops_US", 80, getText (configFile >> "cfgWeapons" >> "H_Cap_tan_specops_US" >> "displayName")],
	["H_Cap_blk_Raven", 80, getText (configFile >> "cfgWeapons" >> "H_Cap_blk_Raven" >> "displayName")],
	["H_Cap_brn_SPECOPS", 80, getText (configFile >> "cfgWeapons" >> "H_Cap_brn_SPECOPS" >> "displayName")],
	["H_Booniehat_dgtl", 80, getText (configFile >> "cfgWeapons" >> "H_Booniehat_dgtl" >> "displayName")],
	["H_Booniehat_tan", 80, getText (configFile >> "cfgWeapons" >> "H_Booniehat_tan" >> "displayName")],
	["H_Hat_tan", 80, getText (configFile >> "cfgWeapons" >> "H_Hat_tan" >> "displayName")],
	["H_Booniehat_oli", 80, getText (configFile >> "cfgWeapons" >> "H_Booniehat_oli" >> "displayName")],
	["H_Booniehat_mcamo", 80, getText (configFile >> "cfgWeapons" >> "H_Booniehat_mcamo" >> "displayName")],
	["H_Booniehat_khk", 80, getText (configFile >> "cfgWeapons" >> "H_Booniehat_khk" >> "displayName")],
	["H_MilCap_ocamo", 80, getText (configFile >> "cfgWeapons" >> "H_MilCap_ocamo" >> "displayName")],
	["H_MilCap_mcamo", 80, getText (configFile >> "cfgWeapons" >> "H_MilCap_mcamo" >> "displayName")],
	["H_MilCap_dgtl", 80, getText (configFile >> "cfgWeapons" >> "H_MilCap_dgtl" >> "displayName")],
	["H_ShemagOpen_tan", 80, getText (configFile >> "cfgWeapons" >> "H_ShemagOpen_tan" >> "displayName")],
	["H_Shemag_olive", 80, getText (configFile >> "cfgWeapons" >> "H_Shemag_olive" >> "displayName")],
	["H_ShemagOpen_khk", 80, getText (configFile >> "cfgWeapons" >> "H_ShemagOpen_khk" >> "displayName")]
];

compil_vestes_civil =
[
	["V_TacVest_oli", 400, getText (configFile >> "cfgWeapons" >> "V_TacVest_oli" >> "displayName")],
	["V_TacVest_blk", 400, getText (configFile >> "cfgWeapons" >> "V_TacVest_blk" >> "displayName")],
	["V_TacVest_brn", 400, getText (configFile >> "cfgWeapons" >> "V_TacVest_brn" >> "displayName")],
	["V_TacVest_khk", 400, getText (configFile >> "cfgWeapons" >> "V_TacVest_khk" >> "displayName")],
	["V_TacVest_camo", 400, getText (configFile >> "cfgWeapons" >> "V_TacVest_camo" >> "displayName")],
	["V_HarnessO_brn", 400, getText (configFile >> "cfgWeapons" >> "V_HarnessO_brn" >> "displayName")],
	["V_HarnessO_gry", 400, getText (configFile >> "cfgWeapons" >> "V_HarnessO_gry" >> "displayName")],
	["V_HarnessOGL_brn", 400, getText (configFile >> "cfgWeapons" >> "V_HarnessOGL_brn" >> "displayName")],
	["V_HarnessOGL_gry", 400, getText (configFile >> "cfgWeapons" >> "V_HarnessOGL_gry" >> "displayName")],
	["V_TacVestIR_blk", 400, getText (configFile >> "cfgWeapons" >> "V_TacVestIR_blk" >> "displayName")],
	["V_RebreatherIA", 400, getText (configFile >> "cfgWeapons" >> "V_RebreatherIA" >> "displayName")],
	["TRYK_LOC_AK_chestrig_OD", 400, getText (configFile >> "cfgWeapons" >> "TRYK_LOC_AK_chestrig_OD" >> "displayName")],
	["TRYK_LOC_AK_chestrig_TAN", 400, getText (configFile >> "cfgWeapons" >> "TRYK_LOC_AK_chestrig_TAN" >> "displayName")],
	["TRYK_V_Bulletproof_BLK", 400, getText (configFile >> "cfgWeapons" >> "TRYK_V_Bulletproof_BLK" >> "displayName")],
	["TRYK_V_ChestRig_L", 400, getText (configFile >> "cfgWeapons" >> "TRYK_V_ChestRig_L" >> "displayName")],
	["TRYK_V_ChestRig", 400, getText (configFile >> "cfgWeapons" >> "TRYK_V_ChestRig" >> "displayName")],
	["TRYK_V_IOTV_BLK", 400, getText (configFile >> "cfgWeapons" >> "TRYK_V_IOTV_BLK" >> "displayName")]
];

compil_sacs_a_dos_civil =
[
	["B_AssaultPack_cbr", 850, getText (configFile >> "cfgVehicles" >> "B_AssaultPack_cbr" >> "displayName")],
	["B_AssaultPack_dgtl", 850, getText (configFile >> "cfgVehicles" >> "B_AssaultPack_dgtl" >> "displayName")],
	["B_AssaultPack_ocamo", 850, getText (configFile >> "cfgVehicles" >> "B_AssaultPack_ocamo" >> "displayName")],
	["B_AssaultPack_khk", 850, getText (configFile >> "cfgVehicles" >> "B_AssaultPack_khk" >> "displayName")],
	["B_AssaultPack_mcamo", 850, getText (configFile >> "cfgVehicles" >> "B_AssaultPack_mcamo" >> "displayName")],
	["B_AssaultPack_blk", 850, getText (configFile >> "cfgVehicles" >> "B_AssaultPack_blk" >> "displayName")],
	["B_AssaultPack_sgg", 850, getText (configFile >> "cfgVehicles" >> "B_AssaultPack_sgg" >> "displayName")],
	["B_AssaultPack_rgr", 850, getText (configFile >> "cfgVehicles" >> "B_AssaultPack_rgr" >> "displayName")],
	["B_FieldPack_cbr", 850, getText (configFile >> "cfgVehicles" >> "B_FieldPack_cbr" >> "displayName")],
	["B_Kitbag_cbr", 850, getText (configFile >> "cfgVehicles" >> "B_Kitbag_cbr" >> "displayName")],
	["B_FieldPack_ocamo", 850, getText (configFile >> "cfgVehicles" >> "B_FieldPack_ocamo" >> "displayName")],
	["B_FieldPack_khk", 850, getText (configFile >> "cfgVehicles" >> "B_FieldPack_khk" >> "displayName")],
	["B_Kitbag_mcamo", 850, getText (configFile >> "cfgVehicles" >> "B_Kitbag_mcamo" >> "displayName")],
	["B_FieldPack_blk", 850, getText (configFile >> "cfgVehicles" >> "B_FieldPack_blk" >> "displayName")],
	["B_FieldPack_oli", 850, getText (configFile >> "cfgVehicles" >> "B_FieldPack_oli" >> "displayName")],
	["B_Kitbag_sgg", 850, getText (configFile >> "cfgVehicles" >> "B_Kitbag_sgg" >> "displayName")],
	["B_Kitbag_rgr", 850, getText (configFile >> "cfgVehicles" >> "B_Kitbag_rgr" >> "displayName")],
	["B_FieldPack_oucamo", 850, getText (configFile >> "cfgVehicles" >> "B_FieldPack_oucamo" >> "displayName")],
	["B_Carryall_ocamo", 850, getText (configFile >> "cfgVehicles" >> "B_Carryall_ocamo" >> "displayName")],
	["B_Carryall_mcamo", 850, getText (configFile >> "cfgVehicles" >> "B_Carryall_mcamo" >> "displayName")],
	["B_Carryall_oli", 850, getText (configFile >> "cfgVehicles" >> "B_Carryall_oli" >> "displayName")],
	["B_Carryall_oucamo", 850, getText (configFile >> "cfgVehicles" >> "B_Carryall_oucamo" >> "displayName")],
	["B_Carryall_cbr", 850, getText (configFile >> "cfgVehicles" >> "B_Carryall_cbr" >> "displayName")],
	["B_Carryall_khk", 850, getText (configFile >> "cfgVehicles" >> "B_Carryall_khk" >> "displayName")],
	["B_TacticalPack_ocamo", 850, getText (configFile >> "cfgVehicles" >> "B_TacticalPack_ocamo" >> "displayName")],
	["B_TacticalPack_mcamo", 850, getText (configFile >> "cfgVehicles" >> "B_TacticalPack_mcamo" >> "displayName")],
	["B_TacticalPack_blk", 850, getText (configFile >> "cfgVehicles" >> "B_TacticalPack_blk" >> "displayName")],
	["B_TacticalPack_oli", 850, getText (configFile >> "cfgVehicles" >> "B_TacticalPack_oli" >> "displayName")],
	["B_TacticalPack_rgr", 850, getText (configFile >> "cfgVehicles" >> "B_TacticalPack_rgr" >> "displayName")]
];

