// =======================================================================================================================================================================================
													// By Maxou - www.sfpteam.fr - INTERDICTION DE RECOPIER !! //
													  // Poursuite pénal possible ! Voir amar.arma3.fr //
// =======================================================================================================================================================================================

waitUntil {alive player};
waitUntil {!isNil "serverID"};
waitUntil {!isnil "fin_verification_apres_chargement"};

sleep 5;

// ====================================================================================================================================================================
								// SAUVEGARDE AUTOMATIQUE OBLIGATOIRE FORCE SEULEMENT SI NOUVEAU JOUEUR //
// ====================================================================================================================================================================
[] spawn 
{
	waitUntil {sleep 1; !isnil "fin_message_amende_valide";}; fin_message_amende_valide = nil;
	if (player getvariable "ma_date_de_naissance" >= 2) exitwith {}; // Exit car valeur déja dans la sauvegarde
	
	// Relecture de la sauvegarde si speudo différent
	[uid_unique_pour_la_sauvegarde, uid_unique_pour_la_sauvegarde, "dernier_speudo_utiliser_news", name player] call fn_SaveToServer;

	// Amende hors ligne
	[uid_pour_mettre_amende, uid_pour_mettre_amende, "Montant de l amende", player getvariable ["montant_de_l_amende", 0]] call fn_SaveToServer;
	[uid_pour_mettre_amende, uid_pour_mettre_amende, "Message amende", player getvariable ["message_amende", 0]] call fn_SaveToServer;
	[uid_pour_mettre_amende, uid_pour_mettre_amende, "Historique nombre amende", player getvariable ["historique_nombre_amende", 0]] call fn_SaveToServer;

	// Remboursement hors ligne
	[uid_pour_remboursement, uid_pour_remboursement, "Montant du remboursement", player getvariable ["montant_du_remboursement", 0]] call fn_SaveToServer;
	[uid_pour_remboursement, uid_pour_remboursement, "Message remboursement", player getvariable ["message_du_remboursement", 0]] call fn_SaveToServer;
	[uid_pour_remboursement, uid_pour_remboursement, "Historique nombre remboursement", player getvariable ["historique_nombre_remboursement", 0]] call fn_SaveToServer;
};

// ====================================================================================================================================================================
														// DETECTION DES PSEUDOS UTILISES ET ENREGISTREMENT //
// ====================================================================================================================================================================
_mes_pseudos_que_j_utilise = player getvariable "mes_pseudos_utilises";
if !(name player in _mes_pseudos_que_j_utilise) then
{
	_mes_pseudos_que_j_utilise = _mes_pseudos_que_j_utilise + [name player];
	
	["Fichier ID Officiel Maxou", "Listes des ID sur le serveur", uid_unique_pour_la_sauvegarde, _mes_pseudos_que_j_utilise] call fn_SaveToServer;
	[uid_unique_pour_la_sauvegarde, uid_unique_pour_la_sauvegarde, "mes_pseudos_utilises", _mes_pseudos_que_j_utilise] call fn_SaveToServer;
	[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "mes_pseudos_utilises", _mes_pseudos_que_j_utilise] call fn_SaveToServer;
	[uid_pour_mettre_amende, uid_pour_mettre_amende, "mes_pseudos_utilises", _mes_pseudos_que_j_utilise] call fn_SaveToServer;
	[uid_pour_remboursement, uid_pour_remboursement, "mes_pseudos_utilises", _mes_pseudos_que_j_utilise] call fn_SaveToServer;
};
// ====================================================================================================================================================================
															// DETECTION LANCEMENT DE LA SAUVEGARDE //
// ====================================================================================================================================================================
// Attente certification pas de bug de sauvegarde
waituntil {sleep 0.2; player getvariable "ma_date_de_naissance" >= 2};
if (relire_toute_ma_sauvegarde == "oui") then {sleep 10;}; // Attente que tout soit remit

while {true} do
{
	forcer_re_sauvegarde = nil;
	
	argent_poche_pour_sav = player getvariable "mon_argent_poche_by_sfp_maxou";
	argent_banque_pour_sav = player getvariable "mon_argent_banque_by_sfp_maxou";
	espace_utilise_pour_sav = player getvariable "usedspace";
	
	integralite_items_pour_sav = itemsWithMagazines player + backpackItems player + vestItems player + uniformItems player + magazines player + weapons player;
	integralite_pour_sav = headgear player + uniform player + vest player + backpack player;
	
	livret_a_pour_sav = player getvariable "mon_livret_a";
	date_de_naissance_pour_sav = player getvariable "ma_date_de_naissance";

	position_pour_sav = getPosATL vehicle player;

	faim_pour_sav = player getvariable "niveau_de_faim";
	nombre_de_permis_pour_sav = player getvariable "nombre_de_permis";
	fatigue_pour_sav = player getvariable "fautdormir";
	envie_de_pipi_pour_sav = player getvariable "toilette_by_sfp_maxou";
	soif_pour_sav = niveau_de_soif;
	niveau_de_cafe_pour_sav = player getvariable "thirstLevel_cafe";
	ma_vie_pour_sav = damage player;
	mon_niveau_secouriste_pour_sav = player getvariable "mon_niveau_secouriste";

	experience_cocaine_pour_sav = player getvariable "experience_transformation_cocaine";
	license_permis_de_conduire_pour_sav = player getvariable "license_permis_de_conduire_by_sfp_maxou";
	point_permis_de_conduire_pour_sav = player getvariable "combien_de_point_by_sfp_maxou";
	license_permis_de_conduire_poid_lourd_pour_sav = player getvariable "license_permis_de_conduire_poids_lourd_by_sfp_maxou";
	
	historique_messages_nom_joueur_by_maxou_pour_sav = historique_messages_nom_joueur_by_maxou;
	
	infraction_wanted_liste_pour_sav = player getvariable "infraction_wanted_liste";
	evader_de_prison_pour_sav = player getvariable "evade_de_prison";
	
	je_possede_un_telephone_sfp_pour_sav = player getvariable "je_possede_un_telephone_sfp";
	etat_verrou_du_groupe_sfp_pour_sav = player getvariable "etat_verrou_du_groupe_sfp";

	espace_total_utilise_pour_sav = player getvariable "totalspace";
	item_fish_pour_sav = player getvariable "item_poissons_sfp";
	item_fish_poisson_panes_pour_sav = player getvariable "itemfishpoissonspanes";
	item_truffle_pour_sav = player getvariable "item_truffe_sfp";
	item_wood_pour_sav = player getvariable "item_bois_sfp";
	item_rabbit_pour_sav = player getvariable "item_lapins_sfp";
	item_serpent_non_transforme_pour_sav = player getvariable "serpent_non_transforme";
	item_serpent_transforme_pour_sav = player getvariable "serpent_transforme";
	item_unpheroin_pour_sav = player getvariable "item_heroine_non_traite_sfp";
	item_cuivre_pour_sav = player getvariable "item_cuivre_non_transforme_sfp";
	item_cuivre_transforme_pour_sav = player getvariable "item_cuivre_transforme_sfp";
	item_pro_heroin_pour_sav = player getvariable "item_heroine_traite_sfp";
	item_plante_illegale_pour_planter_pour_sav = player getvariable "item_plante_pour_planter";
	item_plante_fertilisant_rouge_pour_sav = player getvariable "item_plante_fertilisant_rouge";
	item_plante_illegale_prete_a_vendre_pour_sav = player getvariable "item_plante_illegale_prete_a_vendre_sfp";
	item_whale_pour_sav = player getvariable "item_baleine_sfp";
	item_requin_pour_sav = player getvariable "item_requin_sfp";
	item_cocaine_feuille_de_coca_pour_sav = player getvariable "item_cocaine_feuille_coca_sfp";
	item_cocaine_poudre_pour_sav = player getvariable "item_cocaine_poudre_sfp";
	item_cannabis_non_traite_pour_sav = player getvariable "item_cannabis_non_traite_sfp";
	item_cannabis_traite_pour_sav = player getvariable "item_cannabis_traite_sfp";
	item_medicaments_pour_sav = player getvariable "item_medicaments_sfp";
	item_organes_animaux_pour_sav = player getvariable "item_organes_animaux_sfp";
	item_pommes_pour_sav = player getvariable "item_pomme_sfp";
	item_pomme_de_terre_pour_sav = player getvariable "item_pomme_de_terre_sfp";
	item_sel_pour_sav = player getvariable "item_sel_sfp";
	item_or_traite_pour_sav = player getvariable "item_or_transforme_sfp";
	item_or_non_traite_pour_sav = player getvariable "item_or_non_transforme_sfp";
	item_un_poil_pour_sav = player getvariable "item_petrole_non_traite_sfp";
	item_prooil_pour_sav = player getvariable "item_petrole_traite_sfp";

	item_barre_de_cereal_pour_sav = player getvariable "barredecereale";
	item_bouteille_d_eau_pour_sav = player getvariable "bouteilledeau";
	item_traceur_vehicule_pour_sav = player getvariable "traceur_vehicule";
	item_poignard_item_pour_sav = player getvariable "poignard_item";
	item_corde_et_sac_pour_sav = player getvariable "corde_et_sac";
	item_cocktail_molotov_pour_sav = player getvariable "cocktail_molotov";
	item_brouilleur_sacoche_c4_pour_sav = player getvariable "brouilleur_sacoche_c4";
	item_sacoche_c4_pour_sav = player getvariable "sacoche_de_c4";
	item_redbull_pour_sav = player getvariable "redbull";
	item_canne_a_peche_pour_sav = player getvariable "canne_a_peche";
	item_tente_pour_dormir_pour_sav = player getvariable "tente_pour_dormir";
	item_seau_plante_illegal_pour_sav = player getvariable "seau_plante_illegal";
	item_valise_pour_le_farming_pour_sav = player getvariable "valise_pour_le_farming";
	item_coffre_fort_pour_sav = player getvariable "coffre_fort";
	item_bidon_d_essence_pour_sav = player getvariable "bidon_d_essence";
	item_gants_pour_petrole_pour_sav = player getvariable "gants_pour_petrole";
	item_pied_de_biche_pour_sav = player getvariable "pied_de_biche";
	item_hache_pour_couper_du_bois_pour_sav = player getvariable "hache_pour_coupe_de_bois";
	item_harpon_pour_la_peche_pour_sav = player getvariable "harpon_pour_la_peche";
	item_gellule_amphetamine_pour_sav = player getvariable "gelule_amphetamines";

	temps_de_fatigue_niveau_un_pour_sav = player getvariable "temps_fatigue_niveau_1";
	temps_de_fatigue_niveau_deux_pour_sav = player getvariable "temps_fatigue_niveau_2";
	temps_de_fatigue_niveau_trois_pour_sav = player getvariable "temps_fatigue_niveau_3";
	temps_de_fatigue_niveau_quatre_pour_sav = player getvariable "temps_fatigue_niveau_4";
	temps_de_fatigue_niveau_cinq_pour_sav = player getvariable "temps_fatigue_niveau_5";
	
	niveau_force_pour_sav = player getvariable "niveau_force";

	license_bac_pro_pour_sav = player getvariable "license_BAC_PRO";
	license_bts_pour_sav = player getvariable "license_BTS";
	license_bepc_pour_sav = player getvariable "license_BEPC";
	license_bac_general_pour_sav = player getvariable "license_BAC_GENERAL";
	license_deug_pour_sav = player getvariable "license_DEUG";
	license_bep_mecanique_pour_sav = player getvariable "license_BEP_Mecanique";

	ma_mutuelle_niveau_dix_pour_sav = player getvariable "ma_mutuelle_niveau_10_pour_cent";
	ma_mutuelle_niveau_vingt_cinq_pour_sav = player getvariable "ma_mutuelle_niveau_vingt_cinq_pour_cent";
	ma_mutuelle_niveau_cinquante_pour_sav = player getvariable "ma_mutuelle_niveau_cinquante_pour_cent";
	ma_mutuelle_niveau_soixante_pour_sav = player getvariable "ma_mutuelle_niveau_soixante_quinze_pour_cent";
	ma_mutuelle_niveau_cent_pour_sav = player getvariable "ma_mutuelle_niveau_cent_pour_cent";
	

	waitUntil 
	{
		sleep 0.3;
		(((player getvariable "mon_argent_banque_by_sfp_maxou") - (argent_banque_pour_sav)) >= 1000) or
		((player getvariable "mon_argent_poche_by_sfp_maxou") - (argent_poche_pour_sav) >= 1000) or
		(((argent_banque_pour_sav) - (player getvariable "mon_argent_banque_by_sfp_maxou")) >= 1000) or
		(((argent_poche_pour_sav) - (player getvariable "mon_argent_poche_by_sfp_maxou")) >= 1000) or
		position_pour_sav distance player > 400 or 
		!alive player or 
		espace_utilise_pour_sav != player getvariable "usedspace" or
		count integralite_items_pour_sav != count (itemsWithMagazines player + backpackItems player + vestItems player + uniformItems player + magazines player + weapons player) or
		count integralite_pour_sav != count (headgear player + uniform player + vest player + backpack player) or
		vehicle player != player or
		relire_toute_ma_sauvegarde == "oui" or
		!isnil "forcer_re_sauvegarde"
	};
	
	if (vehicle player != player) then 
	{
		waitUntil 
		{
			sleep 0.3;
			!alive player or 
			vehicle player == player or
			(((player getvariable "mon_argent_banque_by_sfp_maxou") - (argent_banque_pour_sav)) >= 1000) or
			((player getvariable "mon_argent_poche_by_sfp_maxou") - (argent_poche_pour_sav) >= 1000) or
			(((argent_banque_pour_sav) - (player getvariable "mon_argent_banque_by_sfp_maxou")) >= 1000) or
			(((argent_poche_pour_sav) - (player getvariable "mon_argent_poche_by_sfp_maxou")) >= 1000) or
			espace_utilise_pour_sav != player getvariable "usedspace" or
			count integralite_items_pour_sav != count (itemsWithMagazines player + backpackItems player + vestItems player + uniformItems player + magazines player + weapons player) or
			count integralite_pour_sav != count (headgear player + uniform player + vest player + backpack player) or
			relire_toute_ma_sauvegarde == "oui" or
			!isnil "forcer_re_sauvegarde"
		};
	};

	if (!isNull (findDisplay 602)) then
	{
		waitUntil {sleep 0.1; isNull (findDisplay 602) or !alive player or !isnil "forcer_re_sauvegarde"};
	};

// ====================================================================================================================================================================
																	// SAUVEGARDE QUE EN LOCAL //
// ====================================================================================================================================================================
	if (player getvariable "etat_verrou_du_groupe_sfp" != etat_verrou_du_groupe_sfp_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['etat_verrou_du_groupe_sfp', player getvariable "etat_verrou_du_groupe_sfp"] call uid_sauvegarde_ecrire_local_joueur_sfp;};
	
	if (player getvariable "mon_niveau_secouriste" != mon_niveau_secouriste_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['mon_niveau_secouriste', player getvariable "mon_niveau_secouriste"] call uid_sauvegarde_ecrire_local_joueur_sfp;};
	if (player getvariable "niveau_de_faim" != faim_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['niveau_de_faim', player getvariable "niveau_de_faim"] call uid_sauvegarde_ecrire_local_joueur_sfp;};
	if (player getvariable "fautdormir" != fatigue_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['fautdormir', player getvariable "fautdormir"] call uid_sauvegarde_ecrire_local_joueur_sfp;};
	if (player getvariable "toilette_by_sfp_maxou" != envie_de_pipi_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['toilette_by_sfp_maxou', player getvariable "toilette_by_sfp_maxou"] call uid_sauvegarde_ecrire_local_joueur_sfp;};
	if (niveau_de_soif != soif_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['niveau_de_soif', niveau_de_soif] call uid_sauvegarde_ecrire_local_joueur_sfp;};
	if (player getvariable "thirstLevel_cafe" != niveau_de_cafe_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['thirstLevel_cafe', player getvariable "thirstLevel_cafe"] call uid_sauvegarde_ecrire_local_joueur_sfp;};

	if ((count historique_messages_nom_joueur_by_maxou_pour_sav) != (count historique_messages_nom_joueur_by_maxou) or relire_toute_ma_sauvegarde == "oui") then {['historique_messages_nom_joueur_by_maxou', historique_messages_nom_joueur_by_maxou] call uid_sauvegarde_ecrire_local_joueur_sfp;};
	if ((position_pour_sav distance player > 5) or relire_toute_ma_sauvegarde == "oui") then {['getPosATL_vehicle_player', getPosATL vehicle player] call uid_sauvegarde_ecrire_local_joueur_sfp; ['direction_vehicle_player', direction vehicle player] call uid_sauvegarde_ecrire_local_joueur_sfp;};
	
	if (damage player != ma_vie_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['damage_player', damage player] call uid_sauvegarde_ecrire_local_joueur_sfp;};

// ====================================================================================================================================================================
																	// SAUVEGARDE QUE SERVEUR //
// ====================================================================================================================================================================
	if (player getvariable "mon_argent_poche_by_sfp_maxou" != argent_poche_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_pour_la_sauvegarde, uid_unique_pour_la_sauvegarde, "Argent Poche", player getvariable ["mon_argent_poche_by_sfp_maxou", 0]] call fn_SaveToServer;};
	if (player getvariable "mon_argent_banque_by_sfp_maxou" != argent_banque_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_pour_la_sauvegarde, uid_unique_pour_la_sauvegarde, "Argent Banque", player getvariable ["mon_argent_banque_by_sfp_maxou", 0]] call fn_SaveToServer;};
	if (player getvariable "mon_livret_a" != livret_a_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_pour_la_sauvegarde, uid_unique_pour_la_sauvegarde, "Livret A", player getvariable ["mon_livret_a", 0]] call fn_SaveToServer;};
	if (player getvariable "ma_date_de_naissance" != date_de_naissance_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_pour_la_sauvegarde, uid_unique_pour_la_sauvegarde, "ma_date_de_naissance", player getvariable ["ma_date_de_naissance", 0]] call fn_SaveToServer;};

	if (count integralite_items_pour_sav != count (itemsWithMagazines player + backpackItems player + vestItems player + uniformItems player + magazines player + weapons player) or relire_toute_ma_sauvegarde == "oui") then {integralite_items_pour_sav = [player, [player, "maxou_sav_integralite"]] call BIS_fnc_saveInventory; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "integralite_items", integralite_items_pour_sav] call fn_SaveToServer;};
	if (count integralite_pour_sav != count (headgear player + uniform player + vest player + backpack player) or relire_toute_ma_sauvegarde == "oui") then {integralite_pour_sav = [player, [player, "maxou_sav_integralite"]] call BIS_fnc_saveInventory; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "integralite_items", integralite_pour_sav] call fn_SaveToServer;};

	if (player getvariable "usedspace" != espace_utilise_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "usedspace", player getvariable ["usedspace", 0]] call fn_SaveToServer;};
	if (player getvariable "totalspace" != espace_total_utilise_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "totalspace", player getvariable ["totalspace", 0]] call fn_SaveToServer;};
	if (player getvariable "item_poissons_sfp" != item_fish_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_poissons_sfp", player getvariable ["item_poissons_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "itemfishpoissonspanes" != item_fish_poisson_panes_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "itemfishpoissonspanes", player getvariable ["itemfishpoissonspanes", 0]] call fn_SaveToServer;};
	if (player getvariable "item_truffe_sfp" != item_truffle_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_truffe_sfp", player getvariable ["item_truffe_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_bois_sfp" != item_wood_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_bois_sfp", player getvariable ["item_bois_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_lapins_sfp" != item_rabbit_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_lapins_sfp", player getvariable ["item_lapins_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "serpent_non_transforme" != item_serpent_non_transforme_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "serpent_non_transforme", player getvariable ["serpent_non_transforme", 0]] call fn_SaveToServer;};
	if (player getvariable "serpent_transforme" != item_serpent_transforme_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "serpent_transforme", player getvariable ["serpent_transforme", 0]] call fn_SaveToServer;};
	if (player getvariable "item_heroine_non_traite_sfp" != item_unpheroin_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_heroine_non_traite_sfp", player getvariable ["item_heroine_non_traite_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_cuivre_non_transforme_sfp" != item_cuivre_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_cuivre_non_transforme_sfp", player getvariable ["item_cuivre_non_transforme_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_cuivre_transforme_sfp" != item_cuivre_transforme_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_cuivre_transforme_sfp", player getvariable ["item_cuivre_transforme_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_heroine_traite_sfp" != item_pro_heroin_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_heroine_traite_sfp", player getvariable ["item_heroine_traite_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_plante_pour_planter" != item_plante_illegale_pour_planter_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_plante_pour_planter", player getvariable ["item_plante_pour_planter", 0]] call fn_SaveToServer;};
	if (player getvariable "item_plante_fertilisant_rouge" != item_plante_fertilisant_rouge_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_plante_fertilisant_rouge", player getvariable ["item_plante_fertilisant_rouge", 0]] call fn_SaveToServer;};
	if (player getvariable "item_plante_illegale_prete_a_vendre_sfp" != item_plante_illegale_prete_a_vendre_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_plante_illegale_prete_a_vendre_sfp", player getvariable ["item_plante_illegale_prete_a_vendre_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_baleine_sfp" != item_whale_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_baleine_sfp", player getvariable ["item_baleine_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_requin_sfp" != item_requin_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_requin_sfp", player getvariable ["item_requin_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_cocaine_feuille_coca_sfp" != item_cocaine_feuille_de_coca_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_cocaine_feuille_coca_sfp", player getvariable ["item_cocaine_feuille_coca_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_cocaine_poudre_sfp" != item_cocaine_poudre_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_cocaine_poudre_sfp", player getvariable ["item_cocaine_poudre_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_cannabis_non_traite_sfp" != item_cannabis_non_traite_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_cannabis_non_traite_sfp", player getvariable ["item_cannabis_non_traite_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_cannabis_traite_sfp" != item_cannabis_traite_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_cannabis_traite_sfp", player getvariable ["item_cannabis_traite_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_medicaments_sfp" != item_medicaments_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_medicaments_sfp", player getvariable ["item_medicaments_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_organes_animaux_sfp" != item_organes_animaux_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_organes_animaux_sfp", player getvariable ["item_organes_animaux_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_pomme_sfp" != item_pommes_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_pomme_sfp", player getvariable ["item_pomme_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_pomme_de_terre_sfp" != item_pomme_de_terre_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_pomme_de_terre_sfp", player getvariable ["item_pomme_de_terre_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_sel_sfp" != item_sel_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_sel_sfp", player getvariable ["item_sel_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_or_transforme_sfp" != item_or_traite_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_or_transforme_sfp", player getvariable ["item_or_transforme_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_or_non_transforme_sfp" != item_or_non_traite_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_or_non_transforme_sfp", player getvariable ["item_or_non_transforme_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_petrole_non_traite_sfp" != item_un_poil_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_petrole_non_traite_sfp", player getvariable ["item_petrole_non_traite_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "item_petrole_traite_sfp" != item_prooil_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "item_petrole_traite_sfp", player getvariable ["item_petrole_traite_sfp", 0]] call fn_SaveToServer;};

	if (player getvariable "nombre_de_permis" != nombre_de_permis_pour_sav or relire_toute_ma_sauvegarde == "oui") then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "nombre_de_permis", player getvariable ["nombre_de_permis", 0]] call fn_SaveToServer;};

// ====================================================================================================================================================================
																	// SAUVEGARDE QUE SERVEUR + LOCAL //
// ====================================================================================================================================================================
	if (player getvariable "experience_transformation_cocaine" != experience_cocaine_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['experience_transformation_cocaine', player getvariable "experience_transformation_cocaine"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "Experience Cocaine", player getvariable ["experience_transformation_cocaine", 0]] call fn_SaveToServer;};
	if (player getvariable "license_permis_de_conduire_by_sfp_maxou" != license_permis_de_conduire_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['license_permis_de_conduire_by_sfp_maxou', player getvariable "license_permis_de_conduire_by_sfp_maxou"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "License permis de conduire", player getvariable ["license_permis_de_conduire_by_sfp_maxou", 0]] call fn_SaveToServer;};
	if (player getvariable "combien_de_point_by_sfp_maxou" != point_permis_de_conduire_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['combien_de_point_by_sfp_maxou', player getvariable "combien_de_point_by_sfp_maxou"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "Point permis de conduire", player getvariable ["combien_de_point_by_sfp_maxou", 0]] call fn_SaveToServer;};
	if (player getvariable "license_permis_de_conduire_poids_lourd_by_sfp_maxou" != license_permis_de_conduire_poid_lourd_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['license_permis_de_conduire_poids_lourd_by_sfp_maxou', player getvariable "license_permis_de_conduire_poids_lourd_by_sfp_maxouplayer getvariable "] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "License permis lourd", player getvariable ["license_permis_de_conduire_poids_lourd_by_sfp_maxou", 0]] call fn_SaveToServer;};

	if (count (player getvariable "infraction_wanted_liste" ) != count infraction_wanted_liste_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['infraction_wanted_liste', player getvariable "infraction_wanted_liste"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "infraction_wanted_liste", player getvariable ["infraction_wanted_liste", 0]] call fn_SaveToServer;};
	if (player getvariable "evade_de_prison" != evader_de_prison_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['evade_de_prison', player getvariable "evade_de_prison"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "evade_de_prison", player getvariable ["evade_de_prison", 0]] call fn_SaveToServer;};
	
	if (player getvariable "je_possede_un_telephone_sfp" select 0 != je_possede_un_telephone_sfp_pour_sav select 0 or relire_toute_ma_sauvegarde == "oui") then {['je_possede_un_telephone_sfp', player getvariable "je_possede_un_telephone_sfp"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "je_possede_un_telephone_sfp", player getvariable ["je_possede_un_telephone_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "je_possede_un_telephone_sfp" select 1 != je_possede_un_telephone_sfp_pour_sav select 1 or relire_toute_ma_sauvegarde == "oui") then {['je_possede_un_telephone_sfp', player getvariable "je_possede_un_telephone_sfp"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "je_possede_un_telephone_sfp", player getvariable ["je_possede_un_telephone_sfp", 0]] call fn_SaveToServer;};
	if (player getvariable "je_possede_un_telephone_sfp" select 2 != je_possede_un_telephone_sfp_pour_sav select 2 or relire_toute_ma_sauvegarde == "oui") then {['je_possede_un_telephone_sfp', player getvariable "je_possede_un_telephone_sfp"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "je_possede_un_telephone_sfp", player getvariable ["je_possede_un_telephone_sfp", 0]] call fn_SaveToServer;};

	if (player getvariable "barredecereale" != item_barre_de_cereal_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['barredecereale', player getvariable "barredecereale"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "barredecereale", player getvariable ["barredecereale", 0]] call fn_SaveToServer;};
	if (player getvariable "bouteilledeau" != item_bouteille_d_eau_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['bouteilledeau', player getvariable "bouteilledeau"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "bouteilledeau", player getvariable ["bouteilledeau", 0]] call fn_SaveToServer;};
	if (player getvariable "traceur_vehicule" != item_traceur_vehicule_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['traceur_vehicule', player getvariable "traceur_vehicule"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "traceur_vehicule", player getvariable ["traceur_vehicule", 0]] call fn_SaveToServer;};
	if (player getvariable "poignard_item" != item_poignard_item_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['poignard_item', player getvariable "poignard_item"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "poignard_item", player getvariable ["poignard_item", 0]] call fn_SaveToServer;};
	if (player getvariable "corde_et_sac" != item_corde_et_sac_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['corde_et_sac', player getvariable "corde_et_sac"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "corde_et_sac", player getvariable ["corde_et_sac", 0]] call fn_SaveToServer;};
	if (player getvariable "cocktail_molotov" != item_cocktail_molotov_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['cocktail_molotov', player getvariable "cocktail_molotov"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "cocktail_molotov", player getvariable ["cocktail_molotov", 0]] call fn_SaveToServer;};
	if (player getvariable "brouilleur_sacoche_c4" != item_brouilleur_sacoche_c4_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['brouilleur_sacoche_c4', player getvariable "brouilleur_sacoche_c4"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "brouilleur_sacoche_c4", player getvariable ["brouilleur_sacoche_c4", 0]] call fn_SaveToServer;};
	if (player getvariable "sacoche_de_c4" != item_sacoche_c4_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['sacoche_de_c4', player getvariable "sacoche_de_c4"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sacoche_de_c4", player getvariable ["sacoche_de_c4", 0]] call fn_SaveToServer;};
	if (player getvariable "redbull" != item_redbull_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['redbull', player getvariable "redbull"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "redbull", player getvariable ["redbull", 0]] call fn_SaveToServer;};
	if (player getvariable "canne_a_peche" != item_canne_a_peche_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['canne_a_peche', player getvariable "canne_a_peche"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "canne_a_peche", player getvariable ["canne_a_peche", 0]] call fn_SaveToServer;};
	if (player getvariable "tente_pour_dormir" != item_tente_pour_dormir_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['tente_pour_dormir', player getvariable "tente_pour_dormir"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "tente_pour_dormir", player getvariable ["tente_pour_dormir", 0]] call fn_SaveToServer;};
	if (player getvariable "seau_plante_illegal" != item_seau_plante_illegal_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['seau_plante_illegal', player getvariable "seau_plante_illegal"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "seau_plante_illegal", player getvariable ["seau_plante_illegal", 0]] call fn_SaveToServer;};
	if (player getvariable "valise_pour_le_farming" != item_valise_pour_le_farming_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['valise_pour_le_farming', player getvariable "valise_pour_le_farming"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "valise_pour_le_farming", player getvariable ["valise_pour_le_farming", 0]] call fn_SaveToServer;};
	if (player getvariable "coffre_fort" != item_coffre_fort_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['coffre_fort', player getvariable "coffre_fort"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "coffre_fort", player getvariable ["coffre_fort", 0]] call fn_SaveToServer;};
	if (player getvariable "bidon_d_essence" != item_bidon_d_essence_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['bidon_d_essence', player getvariable "bidon_d_essence"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "bidon_d_essence", player getvariable ["bidon_d_essence", 0]] call fn_SaveToServer;};
	if (player getvariable "gants_pour_petrole" != item_gants_pour_petrole_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['gants_pour_petrole', player getvariable "gants_pour_petrole"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "gants_pour_petrole", player getvariable ["gants_pour_petrole", 0]] call fn_SaveToServer;};
	if (player getvariable "pied_de_biche" != item_pied_de_biche_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['pied_de_biche', player getvariable "pied_de_biche"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "pied_de_biche", player getvariable ["pied_de_biche", 0]] call fn_SaveToServer;};
	if (player getvariable "hache_pour_coupe_de_bois" != item_hache_pour_couper_du_bois_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['hache_pour_coupe_de_bois', player getvariable "hache_pour_coupe_de_bois"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "hache_pour_coupe_de_bois", player getvariable ["hache_pour_coupe_de_bois", 0]] call fn_SaveToServer;};
	if (player getvariable "harpon_pour_la_peche" != item_harpon_pour_la_peche_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['harpon_pour_la_peche', player getvariable "harpon_pour_la_peche"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "harpon_pour_la_peche", player getvariable ["harpon_pour_la_peche", 0]] call fn_SaveToServer;};
	if (player getvariable "gelule_amphetamines" != item_gellule_amphetamine_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['gelule_amphetamines', player getvariable "gelule_amphetamines"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "gelule_amphetamines", player getvariable ["gelule_amphetamines", 0]] call fn_SaveToServer;};

	if (player getvariable "temps_fatigue_niveau_1" != temps_de_fatigue_niveau_un_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['temps_fatigue_niveau_1', player getvariable "temps_fatigue_niveau_1"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "temps_fatigue_niveau_1", player getvariable ["temps_fatigue_niveau_1", 0]] call fn_SaveToServer;};
	if (player getvariable "temps_fatigue_niveau_2" != temps_de_fatigue_niveau_deux_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['temps_fatigue_niveau_2', player getvariable "temps_fatigue_niveau_2"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "temps_fatigue_niveau_2", player getvariable ["temps_fatigue_niveau_2", 0]] call fn_SaveToServer;};
	if (player getvariable "temps_fatigue_niveau_3" != temps_de_fatigue_niveau_trois_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['temps_fatigue_niveau_3', player getvariable "temps_fatigue_niveau_3"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "temps_fatigue_niveau_3", player getvariable ["temps_fatigue_niveau_3", 0]] call fn_SaveToServer;};
	if (player getvariable "temps_fatigue_niveau_4" != temps_de_fatigue_niveau_quatre_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['temps_fatigue_niveau_4', player getvariable "temps_fatigue_niveau_4"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "temps_fatigue_niveau_4", player getvariable ["temps_fatigue_niveau_4", 0]] call fn_SaveToServer;};
	if (player getvariable "temps_fatigue_niveau_5" != temps_de_fatigue_niveau_cinq_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['temps_fatigue_niveau_5', player getvariable "temps_fatigue_niveau_5"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "temps_fatigue_niveau_5", player getvariable ["temps_fatigue_niveau_5", 0]] call fn_SaveToServer;};
	
	if (player getvariable "niveau_force" != niveau_force_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['niveau_force', player getvariable 'niveau_force'] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "niveau_force", player getvariable ["niveau_force", 0]] call fn_SaveToServer;};

	if (player getvariable "license_BAC_PRO" != license_bac_pro_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['license_BAC_PRO', player getvariable "license_BAC_PRO"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "license_BAC_PRO", player getvariable ["license_BAC_PRO", 0]] call fn_SaveToServer;};
	if (player getvariable "license_BTS" != license_bts_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['license_BTS', player getvariable "license_BTS"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "license_BTS", player getvariable ["license_BTS", 0]] call fn_SaveToServer;};
	if (player getvariable "license_BEPC" != license_bepc_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['license_BEPC', player getvariable "license_BEPC"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "license_BEPC", player getvariable ["license_BEPC", 0]] call fn_SaveToServer;};
	if (player getvariable "license_BAC_GENERAL" != license_bac_general_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['license_BAC_GENERAL', player getvariable "license_BAC_GENERAL"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "license_BAC_GENERAL", player getvariable ["license_BAC_GENERAL", 0]] call fn_SaveToServer;};
	if (player getvariable "license_DEUG" != license_deug_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['license_DEUG', player getvariable "license_DEUG"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "license_DEUG", player getvariable ["license_DEUG", 0]] call fn_SaveToServer;};
	if (player getvariable "license_BEP_Mecanique" != license_bep_mecanique_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['license_BEP_Mecanique', player getvariable "license_BEP_Mecanique"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "license_BEP_Mecanique", player getvariable ["license_BEP_Mecanique", 0]] call fn_SaveToServer;};

	if (player getvariable "ma_mutuelle_niveau_10_pour_cent" != ma_mutuelle_niveau_dix_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['ma_mutuelle_niveau_10_pour_cent', player getvariable "ma_mutuelle_niveau_10_pour_cent"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "ma_mutuelle_niveau_10_pour_cent", player getvariable ["ma_mutuelle_niveau_10_pour_cent", 0]] call fn_SaveToServer;};
	if (player getvariable "ma_mutuelle_niveau_vingt_cinq_pour_cent" != ma_mutuelle_niveau_vingt_cinq_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['ma_mutuelle_niveau_vingt_cinq_pour_cent', player getvariable "ma_mutuelle_niveau_vingt_cinq_pour_cent"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "ma_mutuelle_niveau_vingt_cinq_pour_cent", player getvariable ["ma_mutuelle_niveau_vingt_cinq_pour_cent", 0]] call fn_SaveToServer;};
	if (player getvariable "ma_mutuelle_niveau_cinquante_pour_cent" != ma_mutuelle_niveau_cinquante_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['ma_mutuelle_niveau_cinquante_pour_cent', player getvariable "ma_mutuelle_niveau_cinquante_pour_cent"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "ma_mutuelle_niveau_cinquante_pour_cent", player getvariable ["ma_mutuelle_niveau_cinquante_pour_cent", 0]] call fn_SaveToServer;};
	if (player getvariable "ma_mutuelle_niveau_soixante_quinze_pour_cent" != ma_mutuelle_niveau_soixante_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['ma_mutuelle_niveau_soixante_quinze_pour_cent', player getvariable "ma_mutuelle_niveau_soixante_quinze_pour_cent"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "ma_mutuelle_niveau_soixante_quinze_pour_cent", player getvariable ["ma_mutuelle_niveau_soixante_quinze_pour_cent", 0]] call fn_SaveToServer;};
	if (player getvariable "ma_mutuelle_niveau_cent_pour_cent" != ma_mutuelle_niveau_cent_pour_sav or relire_toute_ma_sauvegarde == "oui") then {['ma_mutuelle_niveau_cent_pour_cent', player getvariable "ma_mutuelle_niveau_cent_pour_cent"] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "ma_mutuelle_niveau_cent_pour_cent", player getvariable ["ma_mutuelle_niveau_cent_pour_cent", 0]] call fn_SaveToServer;};

// ====================================================================================================================================================================
													// SAUVEGARDE QUE AVEC DES ISNIL SERVEUR + LOCAL //
// ====================================================================================================================================================================
	// Sans profileNamespace
	if (isnil "revive_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "besoin_d_un_revive_news"}) then {[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "Revive_news", true] call fn_SaveToServer;}else{[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "Revive_news", false] call fn_SaveToServer;};};[] spawn {revive_pour_sav = true; if (!isnil {player getvariable "besoin_d_un_revive_news"}) then {waitUntil {sleep 1; isnil {player getvariable "besoin_d_un_revive_news"};};[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "Revive_news", false] call fn_SaveToServer; revive_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 1; !isnil {player getvariable "besoin_d_un_revive_news"}};[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "Revive_news", true] call fn_SaveToServer; revive_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	
	// Avec profileNamespace
	if (isnil "corde_descente_rappel_sfp_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "corde_descente_rappel_sfp"}) then {['corde_descente_rappel_sfp', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "corde_descente_rappel_sfp", true] call fn_SaveToServer;}else{['corde_descente_rappel_sfp', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "corde_descente_rappel_sfp", false] call fn_SaveToServer;};}; [] spawn {corde_descente_rappel_sfp_pour_sav = true; if (!isnil {player getvariable "corde_descente_rappel_sfp"}) then {waitUntil {sleep 4; isnil {player getvariable "corde_descente_rappel_sfp"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "corde_descente_rappel_sfp", false] call fn_SaveToServer; ['corde_descente_rappel_sfp', false] call uid_sauvegarde_ecrire_local_joueur_sfp; corde_descente_rappel_sfp_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "corde_descente_rappel_sfp"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "corde_descente_rappel_sfp", true] call fn_SaveToServer; ['corde_descente_rappel_sfp', true] call uid_sauvegarde_ecrire_local_joueur_sfp; corde_descente_rappel_sfp_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "boite_allumette_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "boite_allumette"}) then {['boite_allumette', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "boite_allumette", true] call fn_SaveToServer;}else{['boite_allumette', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "boite_allumette", false] call fn_SaveToServer;};}; [] spawn {boite_allumette_pour_sav = true; if (!isnil {player getvariable "boite_allumette"}) then {waitUntil {sleep 4; isnil {player getvariable "boite_allumette"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "boite_allumette", false] call fn_SaveToServer; ['boite_allumette', false] call uid_sauvegarde_ecrire_local_joueur_sfp; boite_allumette_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "boite_allumette"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "boite_allumette", true] call fn_SaveToServer; ['boite_allumette', true] call uid_sauvegarde_ecrire_local_joueur_sfp; boite_allumette_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "marteau_sfp_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "marteau_sfp"}) then {['marteau_sfp', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "marteau_sfp", true] call fn_SaveToServer;}else{['marteau_sfp', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "marteau_sfp", false] call fn_SaveToServer;};}; [] spawn {marteau_sfp_pour_sav = true; if (!isnil {player getvariable "marteau_sfp"}) then {waitUntil {sleep 4; isnil {player getvariable "marteau_sfp"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "marteau_sfp", false] call fn_SaveToServer; ['marteau_sfp', false] call uid_sauvegarde_ecrire_local_joueur_sfp; marteau_sfp_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "marteau_sfp"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "marteau_sfp", true] call fn_SaveToServer; ['marteau_sfp', true] call uid_sauvegarde_ecrire_local_joueur_sfp; marteau_sfp_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "jai_fait_un_cambriolage_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "jai_fait_un_cambriolage_news"}) then {['jai_fait_un_cambriolage_news', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "jai_fait_un_cambriolage_news", true] call fn_SaveToServer;}else{['jai_fait_un_cambriolage_news', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "jai_fait_un_cambriolage_news", false] call fn_SaveToServer;};}; [] spawn {jai_fait_un_cambriolage_pour_sav = true; if (!isnil {player getvariable "jai_fait_un_cambriolage_news"}) then {waitUntil {sleep 4; isnil {player getvariable "jai_fait_un_cambriolage_news"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "jai_fait_un_cambriolage_news", false] call fn_SaveToServer; ['jai_fait_un_cambriolage_news', false] call uid_sauvegarde_ecrire_local_joueur_sfp; jai_fait_un_cambriolage_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "jai_fait_un_cambriolage_news"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "jai_fait_un_cambriolage_news", true] call fn_SaveToServer; ['jai_fait_un_cambriolage_news', true] call uid_sauvegarde_ecrire_local_joueur_sfp; jai_fait_un_cambriolage_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "is_wanted_armes_illegales_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "recherche_pour_armes_illegales"}) then {['recherche_pour_armes_illegales', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "recherche_pour_armes_illegales", true] call fn_SaveToServer;}else{['recherche_pour_armes_illegales', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "recherche_pour_armes_illegales", false] call fn_SaveToServer;};}; [] spawn {is_wanted_armes_illegales_pour_sav = true; if (!isnil {player getvariable "recherche_pour_armes_illegales"}) then {waitUntil {sleep 4; isnil {player getvariable "recherche_pour_armes_illegales"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "recherche_pour_armes_illegales", false] call fn_SaveToServer; ['recherche_pour_armes_illegales', false] call uid_sauvegarde_ecrire_local_joueur_sfp; is_wanted_armes_illegales_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "recherche_pour_armes_illegales"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "recherche_pour_armes_illegales", true] call fn_SaveToServer; ['recherche_pour_armes_illegales', true] call uid_sauvegarde_ecrire_local_joueur_sfp; is_wanted_armes_illegales_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "is_wanted_braquage_banque_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "recherche_pour_braquage"}) then {['recherche_pour_braquage', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "recherche_pour_braquage", true] call fn_SaveToServer;}else{['recherche_pour_braquage', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "recherche_pour_braquage", false] call fn_SaveToServer;};}; [] spawn {is_wanted_braquage_banque_pour_sav = true; if (!isnil {player getvariable "recherche_pour_braquage"}) then {waitUntil {sleep 4; isnil {player getvariable "recherche_pour_braquage"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "recherche_pour_braquage", false] call fn_SaveToServer; ['recherche_pour_braquage', false] call uid_sauvegarde_ecrire_local_joueur_sfp; is_wanted_braquage_banque_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "recherche_pour_braquage"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "recherche_pour_braquage", true] call fn_SaveToServer; ['recherche_pour_braquage', true] call uid_sauvegarde_ecrire_local_joueur_sfp; is_wanted_braquage_banque_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "rechercher_conduite_sans_permis_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "recherche_pour_conduite_sans_permis"}) then {['recherche_pour_conduite_sans_permis', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "recherche_pour_conduite_sans_permis", true] call fn_SaveToServer;}else{['recherche_pour_conduite_sans_permis', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "recherche_pour_conduite_sans_permis", false] call fn_SaveToServer;};}; [] spawn {rechercher_conduite_sans_permis_pour_sav = true; if (!isnil {player getvariable "recherche_pour_conduite_sans_permis"}) then {waitUntil {sleep 4; isnil {player getvariable "recherche_pour_conduite_sans_permis"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "recherche_pour_conduite_sans_permis", false] call fn_SaveToServer; ['recherche_pour_conduite_sans_permis', false] call uid_sauvegarde_ecrire_local_joueur_sfp; rechercher_conduite_sans_permis_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "recherche_pour_conduite_sans_permis"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "recherche_pour_conduite_sans_permis", true] call fn_SaveToServer; ['recherche_pour_conduite_sans_permis', true] call uid_sauvegarde_ecrire_local_joueur_sfp; rechercher_conduite_sans_permis_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "arreter_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "joueur_arreter"}) then {['joueur_arreter', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "joueur_arreter", true] call fn_SaveToServer;}else{['joueur_arreter', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "joueur_arreter", false] call fn_SaveToServer;};}; [] spawn {arreter_pour_sav = true; if (!isnil {player getvariable "joueur_arreter"}) then {waitUntil {sleep 4; isnil {player getvariable "joueur_arreter"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "joueur_arreter", false] call fn_SaveToServer; ['joueur_arreter', false] call uid_sauvegarde_ecrire_local_joueur_sfp; arreter_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "joueur_arreter"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "joueur_arreter", true] call fn_SaveToServer; ['joueur_arreter', true] call uid_sauvegarde_ecrire_local_joueur_sfp; arreter_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "maladie_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "je_suis_malade_a_la_sauvegarde"}) then {['je_suis_malade_a_la_sauvegarde', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "je_suis_malade_a_la_sauvegarde", true] call fn_SaveToServer;}else{['je_suis_malade_a_la_sauvegarde', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "je_suis_malade_a_la_sauvegarde", false] call fn_SaveToServer;};}; [] spawn {maladie_pour_sav = true; if (!isnil {player getvariable "je_suis_malade_a_la_sauvegarde"}) then {waitUntil {sleep 4; isnil {player getvariable "je_suis_malade_a_la_sauvegarde"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "je_suis_malade_a_la_sauvegarde", false] call fn_SaveToServer; ['je_suis_malade_a_la_sauvegarde', false] call uid_sauvegarde_ecrire_local_joueur_sfp; maladie_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "je_suis_malade_a_la_sauvegarde"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "je_suis_malade_a_la_sauvegarde", true] call fn_SaveToServer; ['je_suis_malade_a_la_sauvegarde', true] call uid_sauvegarde_ecrire_local_joueur_sfp; maladie_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "menotter_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "joueur_menotte"}) then {['joueur_menotte', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "Joueur Menotte", true] call fn_SaveToServer;}else{['joueur_menotte', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "Joueur Menotte", false] call fn_SaveToServer;};}; [] spawn {menotter_pour_sav = true; if (!isnil {player getvariable "joueur_menotte"}) then {waitUntil {sleep 4; isnil {player getvariable "joueur_menotte"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "Joueur Menotte", false] call fn_SaveToServer; ['joueur_menotte', false] call uid_sauvegarde_ecrire_local_joueur_sfp; menotter_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "joueur_menotte"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "Joueur Menotte", true] call fn_SaveToServer; ['joueur_menotte', true] call uid_sauvegarde_ecrire_local_joueur_sfp; menotter_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_pilote_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "license_pilote_news"}) then {['license_pilote_news', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "license_pilote_news", true] call fn_SaveToServer;}else{['license_pilote_news', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "license_pilote_news", false] call fn_SaveToServer;};}; [] spawn {license_pilote_pour_sav = true; if (!isnil {player getvariable "license_pilote_news"}) then {waitUntil {sleep 4; isnil {player getvariable "license_pilote_news"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "license_pilote_news", false] call fn_SaveToServer; ['license_pilote_news', false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_pilote_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "license_pilote_news"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "license_pilote_news", true] call fn_SaveToServer; ['license_pilote_news', true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_pilote_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_bateau_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "licence_bateau_news"}) then {['licence_bateau_news', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_bateau_news", true] call fn_SaveToServer;}else{['licence_bateau_news', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_bateau_news", false] call fn_SaveToServer;};}; [] spawn {license_bateau_pour_sav = true; if (!isnil {player getvariable "licence_bateau_news"}) then {waitUntil {sleep 4; isnil {player getvariable "licence_bateau_news"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_bateau_news", false] call fn_SaveToServer; ['licence_bateau_news', false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_bateau_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "licence_bateau_news"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_bateau_news", true] call fn_SaveToServer; ['licence_bateau_news', true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_bateau_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "licence_petrole_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "licence_petrole"}) then {['licence_petrole', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_petrole", true] call fn_SaveToServer;}else{['licence_petrole', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_petrole", false] call fn_SaveToServer;};}; [] spawn {licence_petrole_pour_sav = true; if (!isnil {player getvariable "licence_petrole"}) then {waitUntil {sleep 4; isnil {player getvariable "licence_petrole"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_petrole", false] call fn_SaveToServer; ['licence_petrole', false] call uid_sauvegarde_ecrire_local_joueur_sfp; licence_petrole_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "licence_petrole"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_petrole", true] call fn_SaveToServer; ['licence_petrole', true] call uid_sauvegarde_ecrire_local_joueur_sfp; licence_petrole_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_traitement_heroine_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "licence_heroine"}) then {['licence_heroine', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_heroine", true] call fn_SaveToServer;}else{['licence_heroine', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_heroine", false] call fn_SaveToServer;};}; [] spawn {license_traitement_heroine_pour_sav = true; if (!isnil {player getvariable "licence_heroine"}) then {waitUntil {sleep 4; isnil {player getvariable "licence_heroine"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_heroine", false] call fn_SaveToServer; ['licence_heroine', false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_traitement_heroine_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "licence_heroine"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_heroine", true] call fn_SaveToServer; ['licence_heroine', true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_traitement_heroine_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_traitement_cannabis_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "licence_cannabis"}) then {['licence_cannabis', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_cannabis", true] call fn_SaveToServer;}else{['licence_cannabis', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_cannabis", false] call fn_SaveToServer;};}; [] spawn {license_traitement_cannabis_pour_sav = true; if (!isnil {player getvariable "licence_cannabis"}) then {waitUntil {sleep 4; isnil {player getvariable "licence_cannabis"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_cannabis", false] call fn_SaveToServer; ['licence_cannabis', false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_traitement_cannabis_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "licence_cannabis"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_cannabis", true] call fn_SaveToServer; ['licence_cannabis', true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_traitement_cannabis_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_gang_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "licence_gang_v2"}) then {['licence_gang_v2', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_gang_v2", true] call fn_SaveToServer;}else{['licence_gang_v2', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_gang_v2", false] call fn_SaveToServer;};}; [] spawn {license_gang_pour_sav = true; if (!isnil {player getvariable "licence_gang_v2"}) then {waitUntil {sleep 4; isnil {player getvariable "licence_gang_v2"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_gang_v2", false] call fn_SaveToServer; ['licence_gang_v2', false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_gang_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "licence_gang_v2"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_gang_v2", true] call fn_SaveToServer; ['licence_gang_v2', true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_gang_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_chasse_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "permis_de_chasse"}) then {['permis_de_chasse', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "permis_de_chasse", true] call fn_SaveToServer;}else{['permis_de_chasse', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "permis_de_chasse", false] call fn_SaveToServer;};}; [] spawn {license_chasse_pour_sav = true; if (!isnil {player getvariable "permis_de_chasse"}) then {waitUntil {sleep 4; isnil {player getvariable "permis_de_chasse"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "permis_de_chasse", false] call fn_SaveToServer; ['permis_de_chasse', false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_chasse_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "permis_de_chasse"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "permis_de_chasse", true] call fn_SaveToServer; ['permis_de_chasse', true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_chasse_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_pistolet_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "permis_port_d_arme"}) then {['permis_port_d_arme', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "permis_port_d_arme", true] call fn_SaveToServer;}else{['permis_port_d_arme', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "permis_port_d_arme", false] call fn_SaveToServer;};}; [] spawn {license_pistolet_pour_sav = true; if (!isnil {player getvariable "permis_port_d_arme"}) then {waitUntil {sleep 4; isnil {player getvariable "permis_port_d_arme"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "permis_port_d_arme", false] call fn_SaveToServer; ['permis_port_d_arme', false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_pistolet_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "permis_port_d_arme"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "permis_port_d_arme", true] call fn_SaveToServer; ['permis_port_d_arme', true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_pistolet_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "licence_fusils_illegaux_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "licence_fusils_illegaux"}) then {['licence_fusils_illegaux', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_fusils_illegaux", true] call fn_SaveToServer;}else{['licence_fusils_illegaux', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_fusils_illegaux", false] call fn_SaveToServer;};}; [] spawn {licence_fusils_illegaux_pour_sav = true; if (!isnil {player getvariable "licence_fusils_illegaux"}) then {waitUntil {sleep 4; isnil {player getvariable "licence_fusils_illegaux"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_fusils_illegaux", false] call fn_SaveToServer; ['licence_fusils_illegaux', false] call uid_sauvegarde_ecrire_local_joueur_sfp; licence_fusils_illegaux_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "licence_fusils_illegaux"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_fusils_illegaux", true] call fn_SaveToServer; ['licence_fusils_illegaux', true] call uid_sauvegarde_ecrire_local_joueur_sfp; licence_fusils_illegaux_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_fusil_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "licence_fusils"}) then {['licence_fusils', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_fusils", true] call fn_SaveToServer;}else{['licence_fusils', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_fusils", false] call fn_SaveToServer;};}; [] spawn {license_fusil_pour_sav = true; if (!isnil {player getvariable "licence_fusils"}) then {waitUntil {sleep 4; isnil {player getvariable "licence_fusils"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_fusils", false] call fn_SaveToServer; ['licence_fusils', false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_fusil_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "licence_fusils"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "licence_fusils", true] call fn_SaveToServer; ['licence_fusils', true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_fusil_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_car_shop_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "sarl_car_shop"}) then {['sarl_car_shop', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_car_shop", true] call fn_SaveToServer;}else{['sarl_car_shop', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_car_shop", false] call fn_SaveToServer;};}; [] spawn {license_car_shop_pour_sav = true; if (!isnil {player getvariable "sarl_car_shop"}) then {waitUntil {sleep 4; isnil {player getvariable "sarl_car_shop"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_car_shop", false] call fn_SaveToServer; ['sarl_car_shop', false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_car_shop_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "sarl_car_shop"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_car_shop", true] call fn_SaveToServer; ['sarl_car_shop', true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_car_shop_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_depannage_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "sarl_depannage"}) then {['sarl_depannage', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_depannage", true] call fn_SaveToServer;}else{['sarl_depannage', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_depannage", false] call fn_SaveToServer;};}; [] spawn {license_depannage_pour_sav = true; if (!isnil {player getvariable "sarl_depannage"}) then {waitUntil {sleep 4; isnil {player getvariable "sarl_depannage"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_depannage", false] call fn_SaveToServer; ['sarl_depannage', false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_depannage_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "sarl_depannage"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_depannage", true] call fn_SaveToServer; ['sarl_depannage', true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_depannage_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_pompier_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "sarl_pompier"}) then {['sarl_pompier', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_pompier", true] call fn_SaveToServer;}else{['sarl_pompier', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_pompier", false] call fn_SaveToServer;};}; [] spawn {license_pompier_pour_sav = true; if (!isnil {player getvariable "sarl_pompier"}) then {waitUntil {sleep 4; isnil {player getvariable "sarl_pompier"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_pompier", false] call fn_SaveToServer; ['sarl_pompier', false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_pompier_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "sarl_pompier"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_pompier", true] call fn_SaveToServer; ['sarl_pompier', true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_pompier_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_avocat_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "sarl_avocat"}) then {['sarl_avocat', true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_avocat", true] call fn_SaveToServer;}else{['sarl_avocat', false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_avocat", false] call fn_SaveToServer;};}; [] spawn {license_avocat_pour_sav = true; if (!isnil {player getvariable "sarl_avocat"}) then {waitUntil {sleep 4; isnil {player getvariable "sarl_avocat"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_avocat", false] call fn_SaveToServer; ["sarl_avocat", false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_avocat_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "sarl_avocat"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_avocat", true] call fn_SaveToServer; ["sarl_avocat", true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_avocat_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_taxi_g_sept_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "sarl_taxis_gsept"}) then {["sarl_taxis_gsept", true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_taxis_gsept", true] call fn_SaveToServer;}else{["sarl_taxis_gsept", false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_taxis_gsept", false] call fn_SaveToServer;};}; [] spawn {license_taxi_g_sept_pour_sav = true; if (!isnil {player getvariable "sarl_taxis_gsept"}) then {waitUntil {sleep 4; isnil {player getvariable "sarl_taxis_gsept"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_taxis_gsept", false] call fn_SaveToServer; ["sarl_taxis_gsept", false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_taxi_g_sept_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "sarl_taxis_gsept"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_taxis_gsept", true] call fn_SaveToServer; ["sarl_taxis_gsept", true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_taxi_g_sept_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_neomedia_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "sarl_neomedia"}) then {["sarl_neomedia", true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_neomedia", true] call fn_SaveToServer;}else{["sarl_neomedia", false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_neomedia", false] call fn_SaveToServer;};}; [] spawn {license_neomedia_pour_sav = true; if (!isnil {player getvariable "sarl_neomedia"}) then {waitUntil {sleep 4; isnil {player getvariable "sarl_neomedia"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_neomedia", false] call fn_SaveToServer; ["sarl_neomedia", false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_neomedia_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "sarl_neomedia"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_neomedia", true] call fn_SaveToServer; ["sarl_neomedia", true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_neomedia_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "license_auto_ecole_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable "sarl_autoecole"}) then {["sarl_autoecole", true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_autoecole", true] call fn_SaveToServer;}else{["sarl_autoecole", false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_autoecole", false] call fn_SaveToServer;};}; [] spawn {license_auto_ecole_pour_sav = true; if (!isnil {player getvariable "sarl_autoecole"}) then {waitUntil {sleep 4; isnil {player getvariable "sarl_autoecole"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_autoecole", false] call fn_SaveToServer; ["sarl_autoecole", false] call uid_sauvegarde_ecrire_local_joueur_sfp; license_auto_ecole_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable "sarl_autoecole"}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, "sarl_autoecole", true] call fn_SaveToServer; ["sarl_autoecole", true] call uid_sauvegarde_ecrire_local_joueur_sfp; license_auto_ecole_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "famille_une_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable sfp_config_famille_une_nom_pour_variable}) then {[sfp_config_famille_une_nom_pour_variable, true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, sfp_config_famille_une_nom_pour_variable, true] call fn_SaveToServer;}else{[sfp_config_famille_une_nom_pour_variable, false] call uid_sauvegarde_ecrire_local_joueur_sfp;[uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, sfp_config_famille_une_nom_pour_variable, false] call fn_SaveToServer;};}; [] spawn {famille_une_pour_sav = true; if (!isnil {player getvariable sfp_config_famille_une_nom_pour_variable}) then {waitUntil {sleep 4; isnil {player getvariable sfp_config_famille_une_nom_pour_variable}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, sfp_config_famille_une_nom_pour_variable, false] call fn_SaveToServer; [sfp_config_famille_une_nom_pour_variable, false] call uid_sauvegarde_ecrire_local_joueur_sfp; famille_une_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable sfp_config_famille_une_nom_pour_variable}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, sfp_config_famille_une_nom_pour_variable, true] call fn_SaveToServer; [sfp_config_famille_une_nom_pour_variable, true] call uid_sauvegarde_ecrire_local_joueur_sfp; famille_une_pour_sav = nil; forcer_re_sauvegarde = true;};};};
	if (isnil "famille_deux_pour_sav") then {if (relire_toute_ma_sauvegarde == "oui") then {if (!isnil {player getvariable sfp_config_famille_deux_nom_pour_variable}) then {[sfp_config_famille_deux_nom_pour_variable, true] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, sfp_config_famille_deux_nom_pour_variable, true] call fn_SaveToServer;}else{[sfp_config_famille_deux_nom_pour_variable, false] call uid_sauvegarde_ecrire_local_joueur_sfp; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, sfp_config_famille_deux_nom_pour_variable, false] call fn_SaveToServer;};}; [] spawn {famille_deux_pour_sav = true; if (!isnil {player getvariable sfp_config_famille_deux_nom_pour_variable}) then {waitUntil {sleep 4; isnil {player getvariable sfp_config_famille_deux_nom_pour_variable}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, sfp_config_famille_deux_nom_pour_variable, false] call fn_SaveToServer; [sfp_config_famille_deux_nom_pour_variable, false] call uid_sauvegarde_ecrire_local_joueur_sfp; famille_deux_pour_sav = nil; forcer_re_sauvegarde = true;} else {waitUntil {sleep 4; !isnil {player getvariable sfp_config_famille_deux_nom_pour_variable}}; [uid_unique_et_side_pour_la_sauvegarde, uid_unique_et_side_pour_la_sauvegarde, sfp_config_famille_deux_nom_pour_variable, true] call fn_SaveToServer; [sfp_config_famille_deux_nom_pour_variable, true] call uid_sauvegarde_ecrire_local_joueur_sfp; famille_deux_pour_sav = nil; forcer_re_sauvegarde = true;};};};

// ====================================================================================================================================================================
													// FIN //
// ====================================================================================================================================================================
	
	if (relire_toute_ma_sauvegarde == "oui") then {relire_toute_ma_sauvegarde = "non";};
	if (!isnil "forcer_re_sauvegarde") then {systemchat "Forcer sauvegarde complète du personnage ...";};
	if (round (random 5) == 1) then {saveProfileNamespace;};
	
	waitUntil {sleep 0.1; alive player && relire_toute_ma_sauvegarde == "non"};
};