jaidemanderunepiqure = 1;
player removeaction medecinfaismoimal;
sleep 2;
hint "Attention ...";
sleep 2;
hint "J'enfonce l'aiguille ...";
sleep 5;
player setdamage 0.9;
hint "Et voila, un petit peu de, je ne sais pas ce que c'est, te feras pas de mal ;)";
sleep 6;
hint "Patiente un peu, l'effet de la piqure disparaitra bientot et tu retrouveras ta vie ;)";
sleep 7;
player setdamage 0.8;
sleep 7;
player setdamage 0.7;
sleep 7;
player setdamage 0.6;
sleep 7;
player setdamage 0.5;
sleep 7;
player setdamage 0.4;
sleep 7;
player setdamage 0.3;
sleep 7;
player setdamage 0.2;
sleep 7;
player setdamage 0.1;
sleep 7;
player setdamage 0;
hint "L'effet de la piqure est maintenant terminée ! Tu as retrouvés toute ta vie :)";
jaidemanderunepiqure = 0;
